version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-playground}
      POSTGRES_USER: ${POSTGRES_USER:-deuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-depassword}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - init_scripts:/docker-entrypoint-initdb.d
    networks:
      - de-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-deuser} -d ${POSTGRES_DB:-playground}"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@de-playground.local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin123}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "${PGADMIN_PORT:-8082}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - workspace_data:/srv/workspace
      - init_scripts:/srv/init-scripts
    networks:
      - de-network
    depends_on:
      - postgres
      - volume-permissions
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M


  # File manager for easy file access (optional)
  filebrowser:
    image: filebrowser/filebrowser:latest
    user: "1000:1000"  # Use consistent user ID
    environment:
      - FB_DATABASE=/database/filebrowser.db
      - FB_ROOT=/srv
      - FB_NOAUTH=${FILEBROWSER_NOAUTH:-true}
    ports:
      - "${FILEBROWSER_PORT:-8083}:80"
    volumes:
      - filebrowser_data:/database
      - workspace_data:/srv/workspace
      - init_scripts:/srv/init-scripts
    networks:
      - de-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  # Development server with access to the shared workspace, capable of running python and pyspark jobs
  dev-server:
    image: ubuntu:latest
    user: "1000:1000"  # Use consistent user ID
    environment:
      - DE_WORKSPACE=/srv/workspace
    # Expose port to allow ssh access to the server
    ports:
      - "${DEV_SERVER_PORT:-2222}:22"
    network:
      - de-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    # Install necessary packages and set up the workspace
    command: >
      bash -c "apt-get update && apt-get install -y openssh-server python3 python3-pip python3-venv && mkdir -p /var/run/sshd &&
      echo 'root:root' | chpasswd && sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config &&
      sed -i 's/UsePAM yes/UsePAM no/' /etc/ssh/sshd_config &&
      mkdir -p /srv/workspace && chown -R 1000:1000 /srv/workspace &&
      echo 'export DE_WORKSPACE=/srv/workspace' >> /etc/bash.bashrc &&
      echo 'export PATH=$PATH:/srv/workspace/bin' >> /etc/bash.bashrc &&
      service ssh start && tail -f /dev/null"

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  workspace_data:
    driver: local
  init_scripts:
    driver: local
  filebrowser_data:
    driver: local

networks:
  de-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET:-172.20.0.0/16}